### ISSUE TITLE
抓不到自己oj的题。

### ISSUE THREAD

**Issue by csronnie** [zhblue/vjudge#1]
自己的vjudge抓自己oj的题目，總是抓不到。

#hustoj opensource verion instance adapter
hustoj.domain=localhost
hustoj.port=80
hustoj.path=

以上 hustoj.path 是不是Huston local instance 的full path.
可不可以給一個例子。

**Comment by zhblue** [comment]
关注微信公众号onlinejudge
自动回复里有hustoj-liveCD的下载地址。
其中包含最新版本的hustoj和vjudge，并已经配置好可以抓取。
此外最近两个项目代码都有更新，可以更新后尝试。

**Comment by zhblue** [comment]
hustoj.path=是OJ的根目录，留空或/或/JudgeOnline，根据实际情况填写。
总之三个值拼成一个URL，应该可以从VJ服务器上通过这个URL来访问到OJ。
