### ISSUE TITLE
安装问题请教

### ISSUE THREAD

**Issue by xzm2000** [zhblue/vjudge#2]
自己的ubuntu16.04或14.04安装时感觉运行到`echo "waiting for tomcat7 deploying vjudge.war ... 8s count down"`后面就不动了，后面没有任何显示了，不知道是怎么回事，请教下可能的原因，谢谢

**Comment by zhblue** [comment]
是通过远程安装的么？内存有多少？
top看一下内存最大占用的进程是不是java ?

**Comment by xzm2000** [comment]
的确是在云服务器上装的，1G内存的（学生机），正在重置系统盘重新尝试一下

**Comment by xzm2000** [comment]
重置后重新安装正常结束，但是打开对应页面提示

> HTTP Status 404 - /vjudge/
type Status report
message /vjudge/
description The requested resource is not available.
Apache Tomcat/7.0.52 (Ubuntu)

**Comment by zhblue** [comment]
重启看日志
/var/log/nginx/error.log
/var/log/tomcat?/catalina.out

**Comment by xzm2000** [comment]
`/var/log/tomcat?/catalina.out`里主要错误类型有以下的：

>Feb 07, 2019 9:13:49 AM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: ../logs/log4j.log (No such file or directory)
......

> 2019-02-07 09:14:03 WARN  JDBCExceptionReporter:233 - SQL Error: 1698, SQLState: 28000
2019-02-07 09:14:03 ERROR JDBCExceptionReporter:234 - Access denied for user 'root'@'localhost'
2019-02-07 09:14:03 WARN  SettingsFactory:147 - Could not obtain connection to query metadata
java.sql.SQLException: Access denied for user 'root'@'localhost'
......

**Comment by zhblue** [comment]
Access denied for user 'root'@'localhost'  
表示/var/lib/tomcat?/webapps/vjudge/WEB-INF/classes/config.properties
中的数据库账号密码不正确
jdbc.username= root
jdbc.password= root
请修改为正确的账号密码
参考/etc/mysql/debian.cnf

**Comment by oakszyjrnrdy** [comment]
@xzm2000 你好，你最后是改了账号密码就好了吗？我把账号密码改成了能从命令行登录mysql的账号密码，但还是出现老问题。 @zhblue 您能帮帮忙吗？
